### ISSUE TITLE
it's different from Nnightowl in vscode 

### ISSUE THREAD

**Issue by khoshroomahdi** [edurojasr/Windows_Terminal_Theme_Night_Owl#3]
foreground colors is different and i prefer vscode color in nightowl.
how can ic change it.
![Screenshot 2020-10-31 233210](https://user-images.githubusercontent.com/20259070/97788860-45514180-1bd1-11eb-8cd8-9ddc92d8a23a.png)

**Comment by edurojasr** [comment]
Hi @khoshroomahdi 

The foreground colors are diferent form the text editor vs the terminal, here is a screenshot of the terminal in VS Code

![100756](https://user-images.githubusercontent.com/35645729/97891791-d8cf6300-1cf4-11eb-8f17-9dc2215db59e.png)

As you may see this theme follow the scheme of colors of the terminal in VS Code, you may try change some values to make it looks like the text editor, but this can introduce inconsistence's since the terminal have a much more limited color options than the text editor. 

Probably I  going to try to make it look like the text editor after testing.

**Comment by khoshroomahdi** [comment]
I thinks its related to powershell scheme. Not terminal.

**Comment by khoshroomahdi** [comment]
I really appreciate if you try this.
🌹

**Comment by edurojasr** [comment]
Yes I will do it this weekend and see how its go, remember that for some reason its shell (powershell, bash, cmd) have its own colors

**Comment by edurojasr** [comment]
Hi @khoshroomahdi 

I did some test look the results 

![Screenshot 2020-11-20 104036](https://user-images.githubusercontent.com/35645729/99826813-7791f700-2b1e-11eb-8bb7-022c853ed769.png)



I get pretty close to the text editor colors, the problem is that you have to ignore the color parameters of the terminal 

"schemes": [
        {
            "background": "#011627",
            "black": "#011627",
            "blue": "#82AAFF",
            "brightBlack": "#969696",
            "brightBlue": "#82AAFF",
            "brightCyan": "#7FDBCA",
            **"brightGreen": "#C792EA"**,
            "brightPurple": "#C792EA",
            "brightRed": "#EF5350",
            "brightWhite": "#82AAFF",
            "brightYellow": "#FFEB95",
            "cyan": "#21C7A8",
            **"foreground": "#82AAFF"**,
            "green": "#22DA6E",
            "name": "Night Owl",
            "purple": "#C792EA",
            "red": "#EF5350",
            "white": "#82AAFF",
            "yellow": "#ADDB67"
        },,

What I did its simple, just repeat the purple color in the "brightGreen" parameter and the blue in the "foreground" parameter, you get a much closer look like the text editor, the obvious problem its that you lose the green and the blue is now a mess. This is the reason I follow the vscode terminal color scheme to avoid conflict colors.
